# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'HumanaDeployment'
    subscriptionId: '21196cdf-abb2-4697-9f73-feef0db7cb2a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'deployment-repro'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'LAv2-vNet\templates\azuredeploy.json'
    csmParametersFile: 'LAv2-vNet\templates\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deployment-repro'